### PR TITLE
Petit refactoring

### PR DESCRIPTION
**Pull request by yhirano55**
This is the good gem to test with BigQuery.
But, some codes are not good a little, so I try to refactor it.

If it's no problems, merge it please. Thanks.

### CODE REVIEW

**Comment by yuemori** [comment]
Thanks to contribute.
Great!

And sorry, your test failed cause to do not good travis setting.
I already fixed settings.
Please rebase and re-push, thanks.

**Comment by yuemori** [comment]
I'm happy to if you would remove Hashie from Gemfile.

**Comment by yhirano55** [comment]
Thank you for your reply.
I have re-pushed this PR. Please merge it.

**Comment by yuemori** [comment]
Fantstic!

**Pull request merged**
